name: "artifacts cleanup"
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 20 * * *" # UTC

jobs:
  purge-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 30 minutes
